In [1]:
# Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
# standard deviation of the dataset using NumPy's functions.

import numpy as np

# Create a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute the mean using np.mean()
mean = np.mean(dataset)

# Compute the median using np.median()
median = np.median(dataset)

# Compute the variance using np.var()
variance = np.var(dataset)

# Compute the standard deviation using np.std()
std_deviation = np.std(dataset)

# Print the computed statistics
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)


Mean: 507.8
Median: 531.0
Variance: 95220.29999999999
Standard Deviation: 308.5778669963223


In [2]:
# Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

import numpy as np

# Generate an array of 50 random numbers between 1 and 100
dataset = np.random.randint(1, 101, size=50)

# Find the 25th percentile using np.percentile()
percentile_25 = np.percentile(dataset, 25)

# Find the 75th percentile using np.percentile()
percentile_75 = np.percentile(dataset, 75)

# Print the computed percentiles
print("25th percentile:", percentile_25)
print("75th percentile:", percentile_75)


25th percentile: 28.0
75th percentile: 76.75


In [3]:
#  Create two arrays representing two sets of variables. Compute the correlation coefficient between these
# arrays using NumPy's `corrcoef` function .

import numpy as np

# Create two arrays representing two sets of variables
set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([2, 4, 6, 8, 10])

# Compute the correlation coefficient between the two arrays using np.corrcoef()
correlation_coefficient = np.corrcoef(set1, set2)[0, 1]

# Print the computed correlation coefficient
print("Correlation coefficient between the two arrays:", correlation_coefficient)


Correlation coefficient between the two arrays: 0.9999999999999999


In [4]:
# Create two matrices and perform matrix multiplication using NumPy's `dot` function.

import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3],
                     [4, 5, 6]])

matrix2 = np.array([[7, 8],
                     [9, 10],
                     [11, 12]])

# Perform matrix multiplication using np.dot()
result = np.dot(matrix1, matrix2)

# Print the result
print("Result of matrix multiplication:")
print(result)


Result of matrix multiplication:
[[ 58  64]
 [139 154]]


In [5]:
# Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles 
# along with the first and third quartiles .

import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3],
                     [4, 5, 6]])

matrix2 = np.array([[7, 8],
                     [9, 10],
                     [11, 12]])

# Perform matrix multiplication using np.dot()
result = np.dot(matrix1, matrix2)

# Print the result
print("Result of matrix multiplication:")
print(result)


Result of matrix multiplication:
[[ 58  64]
 [139 154]]


In [6]:
# Create a NumPy array of integers and find the index of a specific element.

import numpy as np

# Create a NumPy array of integers
array = np.array([10, 20, 30, 40, 50])

# Find the index of a specific element
element_to_find = 30
index = np.where(array == element_to_find)[0]

# Print the index of the element
print("Index of", element_to_find, ":", index)


Index of 30 : [2]


In [7]:
# Generate a random NumPy array and sort it in ascending order.

import numpy as np

# Generate a random NumPy array
random_array = np.random.randint(1, 100, size=10)

# Sort the array in ascending order using np.sort()
sorted_array = np.sort(random_array)

# Print the sorted array
print("Sorted array in ascending order:")
print(sorted_array)


Sorted array in ascending order:
[14 19 22 33 36 39 73 80 87 99]


In [8]:
#  Filter elements >20  in the given NumPy array.
#      arr = np.array([12, 25, 6, 42, 8, 30])

import numpy as np

# Given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_arr = arr[arr > 20]

# Print the filtered array
print("Filtered array with elements greater than 20:")
print(filtered_arr)


Filtered array with elements greater than 20:
[25 42 30]


In [9]:
#  Filter elements which are divisible by 3 from a given NumPy array.
#            arr = np.array([1, 5, 8, 12, 15])

import numpy as np

# Given NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_arr = arr[arr % 3 == 0]

# Print the filtered array
print("Filtered array with elements divisible by 3:")
print(filtered_arr)


Filtered array with elements divisible by 3:
[12 15]


In [10]:
# Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
#         arr = np.array([10, 20, 30, 40, 50])

import numpy as np

# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements between 20 and 40
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

# Print the filtered array
print("Filtered array with elements between 20 and 40 (inclusive):")
print(filtered_arr)


Filtered array with elements between 20 and 40 (inclusive):
[20 30 40]


In [11]:
#  For the given NumPy array, check its byte order using the `dtype` attribute byteorder
#                    arr = np.array([1, 2, 3])

import numpy as np

# Given NumPy array
byteorderarr = np.array([1, 2, 3])

# Check the byte order using dtype attribute
byte_order = byteorderarr.dtype.byteorder

# Print the byte order
print("Byte order of the array:", byte_order)


Byte order of the array: =


In [13]:
# For the given NumPy array, perform byte swapping in place using `byteswap()`.
#                 arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(True)

# Print the modified array after byte swapping
print("Modified array after byte swapping:", arr)



Modified array after byte swapping: [16777216 33554432 50331648]


In [14]:
#  For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
#                       arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap byte order without modifying the original array
arr_swapped = arr.newbyteorder()

# Print the array with swapped byte order
print("Original array:", arr)
print("Array with swapped byte order:", arr_swapped)


Original array: [1 2 3]
Array with swapped byte order: [16777216 33554432 50331648]


In [15]:
# For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
#                        arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np
import sys

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Get the system endianness
system_endianness = sys.byteorder

# Swap byte order conditionally based on system endianness
arr_swapped = arr.newbyteorder(system_endianness)

# Print the array with swapped byte order
print("Original array:", arr)
print("Array with swapped byte order based on system endianness:", arr_swapped)


Original array: [1 2 3]
Array with swapped byte order based on system endianness: [1 2 3]


In [16]:
#  For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute
# `byteorder`.
#                         arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Check if byte swapping is necessary based on system endianness
byte_order = arr.dtype.byteorder

if byte_order == '=':
    print("Byte swapping is not necessary for the current system.")
else:
    print("Byte swapping is necessary for the current system.")


Byte swapping is not necessary for the current system.


In [17]:
#  Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

import numpy as np

# Create NumPy array arr1 with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of arr1 named copy_arr
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

# Check if modifying copy_arr affects arr1
print("Original arr1:", arr1)
print("Modified copy_arr:", copy_arr)


Original arr1: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy_arr: [100   2   3   4   5   6   7   8   9  10]


In [18]:
# Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

import numpy as np

# Create a 2D NumPy array matrix of shape (3, 3) with random integers
matrix = np.random.randint(1, 10, size=(3, 3))

# Extract a slice view_slice from the matrix
view_slice = matrix[:2, :2]

# Modify an element in view_slice
view_slice[0, 0] = 100

# Check if modifying view_slice changes the original matrix
print("Original matrix:")
print(matrix)

print("\nModified view_slice:")
print(view_slice)


Original matrix:
[[100   5   2]
 [  6   9   6]
 [  5   9   2]]

Modified view_slice:
[[100   5]
 [  6   9]]


In [19]:
#  Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

import numpy as np

# Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice view_b from array_a
view_b = array_a[:2, :2]

# Broadcast the addition of 5 to view_b
view_b += 5

# Check if it alters the original array_a
print("Original array_a:")
print(array_a)

print("\nModified view_b:")
print(view_b)


Original array_a:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]

Modified view_b:
[[ 6  7]
 [ 9 10]]


In [20]:
# Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
# reflects changes in the original `orig_array`.

import numpy as np

# Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view reshaped_view of shape (4, 2) from orig_array
reshaped_view = orig_array.T.reshape(4, 2)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 100

# Check if it reflects changes in the original orig_array
print("Original orig_array:")
print(orig_array)

print("\nModified reshaped_view:")
print(reshaped_view)


Original orig_array:
[[100   2   3   4]
 [  5   6   7   8]]

Modified reshaped_view:
[[100   5]
 [  2   6]
 [  3   7]
 [  4   8]]


In [22]:
# Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

import numpy as np

# Create a NumPy array data of shape (3, 4) with random integers
data = np.random.randint(1, 10, size=(3, 4))

# Extract a copy data_copy of elements greater than 5
data_copy = data[data > 5].copy()

# Modify an element in data_copy
data_copy[0] = 100

# Verify if it affects the original data
print("Original data:")
print(data)

print("\nModified data_copy:")
print(data_copy)


Original data:
[[5 7 4 6]
 [4 8 8 8]
 [7 4 5 6]]

Modified data_copy:
[100   6   8   8   8   7   6]


In [23]:
# Create two matrices A and B of identical shape containing integers and perform addition and subtraction
# operations between them.

import numpy as np

# Create matrices A and B of identical shape containing integers
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

# Perform addition operation between A and B
addition_result = A + B

# Perform subtraction operation between A and B
subtraction_result = A - B

# Display the results
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition Result (A + B):")
print(addition_result)

print("\nSubtraction Result (A - B):")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Addition Result (A + B):
[[ 8 10 12]
 [14 16 18]]

Subtraction Result (A - B):
[[-6 -6 -6]
 [-6 -6 -6]]


In [24]:
# Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

import numpy as np

# Generate matrix C (3x2) and matrix D (2x4)
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

# Perform matrix multiplication
multiplication_result = np.dot(C, D)

# Display the result
print("Matrix C:")
print(C)

print("\nMatrix D:")
print(D)

print("\nMatrix Multiplication (C x D):")
print(multiplication_result)


Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix D:
[[ 7  8  9 10]
 [11 12 13 14]]

Matrix Multiplication (C x D):
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [25]:
# Create a matrix `E` and find its transpose.

import numpy as np

# Create matrix E
E = np.array([[1, 2, 3],
              [4, 5, 6]])

# Find the transpose of matrix E
transpose_E = np.transpose(E)

# Display the original matrix E and its transpose
print("Matrix E:")
print(E)

print("\nTranspose of Matrix E:")
print(transpose_E)


Matrix E:
[[1 2 3]
 [4 5 6]]

Transpose of Matrix E:
[[1 4]
 [2 5]
 [3 6]]


In [26]:
# Generate a square matrix `F` and compute its determinant.

import numpy as np

# Generate a square matrix F
F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)

# Display the original matrix F and its determinant
print("Matrix F:")
print(F)

print("\nDeterminant of Matrix F:", determinant_F)


Matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of Matrix F: 0.0


In [28]:
# Create a square matrix `G` and find its inverse.

import numpy as np

# Create a square matrix G
G = np.array([[1, 2],
              [3, 4]])

# Find the inverse of matrix G
inverse_G = np.linalg.inv(G)

# Display the original matrix G and its inverse
print("Matrix G:")
print(G)

print("\nInverse of Matrix G:")
print(inverse_G)


Matrix G:
[[1 2]
 [3 4]]

Inverse of Matrix G:
[[-2.   1. ]
 [ 1.5 -0.5]]
