In [1]:
# Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np
# Create a NumPy array of integers from 0 to 5
arr = np.array([0, 1, 2, 3, 4, 5])

# Print the data type of the array
print("Data type of 'arr':", arr.dtype)

<class 'list'>


In [3]:
#  Given a NumPy array 'arr', check if its data type is float64.
  # arr = np.array([1.5, 2.6, 3.7])
    
import numpy as np    
# Given NumPy array
arr = np.array([1.5, 2.6, 3.7])

# Check if the data type of the array is float64
if arr.dtype == np.float64:
    print("The data type of 'arr' is float64.")
else:
    print("The data type of 'arr' is not float64.")


The data type of 'arr' is float64.


In [6]:
# Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

import numpy as np

# Create a NumPy array with complex numbers
arr = np.array([2 + 3j, 4 - 2j, 5 + 1j], dtype=np.complex128)

# Print the array
print("NumPy array 'arr' with complex numbers:\n", arr)


NumPy array 'arr' with complex numbers:
 [2.+3.j 4.-2.j 5.+1.j]


In [2]:
# Convert an existing NumPy array 'arr' of integers to float32 data type.

import numpy as np

# Assuming 'arr' is your existing NumPy array of integers
arr = np.array([1, 2, 3, 4, 5])

# Convert the data type of 'arr' to float32
arr_float32 = arr.astype(np.float32)

# Print the converted array
print("Original array:\n", arr)
print("\nArray after conversion to float32:\n", arr_float32)



Original array:
 [1 2 3 4 5]

Array after conversion to float32:
 [1. 2. 3. 4. 5.]


In [3]:
# Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

import numpy as np

# Assuming 'arr' is your existing NumPy array with float64 data type
arr = np.array([1.5, 2.6, 3.7])

# Convert the data type of 'arr' to float32
arr_float32 = arr.astype(np.float32)

# Print the converted array
print("Original array:\n", arr)
print("\nArray after conversion to float32:\n", arr_float32)

Original array:
 [1.5 2.6 3.7]

Array after conversion to float32:
 [1.5 2.6 3.7]


In [4]:
# Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype.

import numpy as np

def array_attributes(arr):
    """
    Returns the shape, size, and data type of a NumPy array.
    
    Parameters:
        arr (numpy.ndarray): Input NumPy array.
    
    Returns:
        tuple: A tuple containing the shape, size, and data type of the array.
    """
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype

my_array = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(my_array)
print("Shape of the array:", shape)
print("Size of the array:", size)
print("Data type of the array:", dtype)

Shape of the array: (2, 3)
Size of the array: 6
Data type of the array: int64


In [5]:
# Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

import numpy as np

def array_dimension(arr):
    """
    Returns the dimensionality of a NumPy array.
    
    Parameters:
        arr (numpy.ndarray): Input NumPy array.
    
    Returns:
        int: The dimensionality of the array.
    """
    return arr.ndim

my_array = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(my_array)
print("Dimensionality of the array:", dimension)

Dimensionality of the array: 2


In [11]:
# Design a function item_size_info that takes a NumPy array as input and returns the item size and
# the total size in bytes.

import numpy as np

def item_size_info(arr):
    """
    Returns the item size and total size in bytes of a NumPy array.
    
    Parameters:
        arr (numpy.ndarray): Input NumPy array.
    
    Returns:
        tuple: A tuple containing the item size and total size in bytes of the array.
    """
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size

my_array = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size_info(my_array)
print("Item size of the array:", item_size)
print("Total size of the array (in bytes):", total_size)

Item size of the array: 8
Total size of the array (in bytes): 48


In [14]:
#  Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

import numpy as np

def array_strides(arr):
    """
    Returns the strides of a NumPy array.
    
    Parameters:
        arr (numpy.ndarray): Input NumPy array.
    
    Returns:
        tuple: A tuple containing the strides of the array.
    """
    return arr.strides

# Example usage:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(my_array)
print("Strides of the array:", strides)

Strides of the array: (24, 8)


In [17]:
# Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
# and strides of the array.

import numpy as np

def shape_strides_relationship(arr):
    shape = arr.shape
    stride = arr.strides
    return shape, strides

my_array = np.array([[3,4,5],[6,7,8]])
shape, strides = shape_strides_relationship(my_array)
print ("shape of the array:" ,shape)
print("srtides of the array:" ,strides)

shape of the array: (2, 3)
srtides of the array: (24, 8)


In [2]:
# Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
# zeros with `n` elements.

import numpy as np

def create_zeros_array(n):
    """
    Creates a NumPy array of zeros with n elements.
    
    Parameters:
        n (int): Number of elements in the array.
    
    Returns:
        numpy.ndarray: NumPy array of zeros with n elements.
    """
    return np.zeros(n)

n = 5
zeros_array = create_zeros_array(n)
print("NumPy array of zeros with", n, "elements:", zeros_array)

NumPy array of zeros with 5 elements: [0. 0. 0. 0. 0.]


In [5]:
# Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
# NumPy array filled with ones of size `rows x cols`.

import numpy as np

def create_ones_matrix(rows, cols):
    """
    Creates a 2D NumPy array filled with ones of size rows x cols.
    
    Parameters:
        rows (int): Number of rows in the matrix.
        cols (int): Number of columns in the matrix.
    
    Returns:
        numpy.ndarray: 2D NumPy array filled with ones of size rows x cols.
    """
    return np.ones((rows, cols))

rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print("2D NumPy array filled with ones of size", rows, "x", cols, ":\n", ones_matrix)


2D NumPy array filled with ones of size 3 x 4 :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
#creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified step.

import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start ,stop, step)

start =1
stop =10
step =2
range_array = generate_range_array(start, stop, step)
print("NumPy array with range starting from", start, "to", stop - 1, "with step", step, ":\n", range_array)

NumPy array with range starting from 1 to 9 with step 2 :
 [1 3 5 7 9]


In [4]:
# Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
#arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

import numpy as np

def generate_linear_space(start, stop, num):
    """
    Generates a NumPy array with num equally spaced values between start and stop (inclusive).
    
    Parameters:
        start (float): Starting value of the linear space.
        stop (float): Ending value of the linear space.
        num (int): Number of values to generate between start and stop.
    
    Returns:
        numpy.ndarray: NumPy array containing the generated linear space.
    """
    return np.linspace(start, stop, num)

start = 1.0
stop = 5.0
num = 10
linear_space_array = generate_linear_space(start, stop, num)
print("NumPy array with linear space starting from", start, "to", stop, "with", num, "values:\n", linear_space_array)

NumPy array with linear space starting from 1.0 to 5.0 with 10 values:
 [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [5]:
#  Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix 
# of size `n x n` using `numpy.eye`.

import numpy as np

def create_identity_matrix(n) :
    return np.eye(n)

n = 5
identity_matrix = create_identity_matrix(n)
print("Square identity matrix of size", n, "x", n, ":\n", identity_matrix)


Square identity matrix of size 5 x 5 :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
#  Write a function that takes a Python list and converts it into a NumPy array.

import numpy as np

def list_to_numpy_array(input_list):
    """
    Converts a Python list into a NumPy array.
    
    Parameters:
        input_list (list): The Python list to be converted.
    
    Returns:
        numpy.ndarray: The NumPy array created from the input list.
    """
    return np.array(input_list)

my_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(my_list)
print("NumPy array created from the Python list:", numpy_array)

NumPy array created from the Python list: [1 2 3 4 5]


In [15]:
# Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Use numpy.view to create a new array object with the same data
view_array = original_array.view()

# Print both arrays
print("Original array:", original_array)
print("View array:", view_array)

Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]


In [22]:
# Write a function that takes two NumPy arrays and concatenates them along a specified axis.

import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    """
    Concatenates two NumPy arrays along the specified axis.
    
    Parameters:
        arr1 (numpy.ndarray): The first NumPy array.
        arr2 (numpy.ndarray): The second NumPy array.
        axis (int, optional): The axis along which to concatenate the arrays.
            Default is 0 (concatenation along the first axis).
    
    Returns:
        numpy.ndarray: The concatenated NumPy array.
    """
    return np.concatenate((arr1, arr2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
concatenated_array = concatenate_arrays(array1, array2, axis=0)
print("Concatenated array along axis 0:\n", concatenated_array)



Concatenated array along axis 0:
 [[1 2]
 [3 4]
 [5 6]]


In [20]:
# Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

import numpy as np

# Create two NumPy arrays with different shapes
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8],
                   [9, 10]])

# Concatenate the arrays horizontally
concatenated_array = np.concatenate((array1, array2), axis=1)

# Print the concatenated array
print("Concatenated array horizontally:\n", concatenated_array)




Concatenated array horizontally:
 [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [24]:
# Write a function that vertically stacks multiple NumPy arrays given as a list

import numpy as np

def vertical_stack_arrays(arrays):
    """
    Vertically stacks multiple NumPy arrays given as a list.
    
    Parameters:
        arrays (list of numpy.ndarray): List containing NumPy arrays to be vertically stacked.
    
    Returns:
        numpy.ndarray: Vertically stacked NumPy array.
    """
    return np.vstack(arrays)

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

array3 = np.array([[13, 14, 15],
                   [16, 17, 18]])

stacked_array = vertical_stack_arrays([array1, array2, array3])
print("Vertically stacked array:\n", stacked_array)


Vertically stacked array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
