In [1]:
#  Calculate column wise mean for the given array:
#       arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate column-wise mean
column_means = np.mean(arr, axis=0)

print("Column-wise mean:")
print(column_means)


Column-wise mean:
[2.5 3.5 4.5]


In [1]:
#  Find maximum value in each row of the given array:
#      arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find maximum value in each row
row_max_values = np.max(arr, axis=1)

print("Maximum value in each row:")
print(row_max_values)


Maximum value in each row:
[3 6]


In [2]:
# For the given array, find indices of maximum value in each column.
#      arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find indices of maximum value in each column
column_max_indices = np.argmax(arr, axis=0)

print("Indices of maximum value in each column:")
print(column_max_indices)


Indices of maximum value in each column:
[1 1 1]


In [3]:
# For the given array, apply custom function to calculate moving sum along rows.
#       arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Custom function to calculate moving sum along rows
def moving_sum(row):
    return np.convolve(row, np.ones(3), mode='valid')

# Apply the custom function along rows
moving_sum_result = np.apply_along_axis(moving_sum, axis=1, arr=arr)

print("Moving sum along rows:")
print(moving_sum_result)


Moving sum along rows:
[[ 6.]
 [15.]]


In [4]:
#  In the given array, check if all elements in each column are even.
#           arr = np.array([[2, 4, 6], [3, 5, 7]])

import numpy as np

# Given array
arr = np.array([[2, 4, 6],
                [3, 5, 7]])

# Check if all elements in each column are even
column_even = np.all(arr % 2 == 0, axis=0)

print("Are all elements in each column even?")
print(column_even)


Are all elements in each column even?
[False False False]


In [5]:
#  Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
#         original_array = np.array([1, 2, 3, 4, 5, 6])

import numpy as np

# Given original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Define the desired dimensions for the reshaped matrix
m = 2  # Number of rows
n = 3  # Number of columns

# Reshape the original array into a matrix of dimensions m rows and n columns
reshaped_matrix = original_array.reshape(m, n)

print("Reshaped matrix:")
print(reshaped_matrix)






Reshaped matrix:
[[1 2 3]
 [4 5 6]]


In [6]:
# Create a function that takes a matrix as input and returns the flattened array.
#        input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

def flatten_matrix(input_matrix):
    """
    Function to flatten a matrix into a 1D array.
    
    Parameters:
        input_matrix (numpy.ndarray): Input matrix.
        
    Returns:
        numpy.ndarray: Flattened array.
    """
    # Flatten the input matrix
    flattened_array = input_matrix.flatten()
    
    return flattened_array

# Given input matrix
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Call the function and print the flattened array
flattened_array = flatten_matrix(input_matrix)
print("Flattened array:")
print(flattened_array)


Flattened array:
[1 2 3 4 5 6]


In [7]:
# Write a function that concatenates two given arrays along a specified axis.
#                array1 = np.array([[1, 2], [3, 4]])
#                array2 = np.array([[5, 6], [7, 8]])

import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    """
    Function to concatenate two arrays along a specified axis.
    
    Parameters:
        array1 (numpy.ndarray): First array.
        array2 (numpy.ndarray): Second array.
        axis (int, optional): Axis along which arrays will be concatenated. Default is 0.
        
    Returns:
        numpy.ndarray: Concatenated array.
    """
    concatenated_array = np.concatenate((array1, array2), axis=axis)
    return concatenated_array

# Given arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Call the function and print the concatenated array along axis 0
concatenated_array_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated array along axis 0:")
print(concatenated_array_axis0)

# Call the function and print the concatenated array along axis 1
concatenated_array_axis1 = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated array along axis 1:")
print(concatenated_array_axis1)


Concatenated array along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated array along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [1]:
#  Create a function that splits an array into multiple sub-arrays along a specified axis.
#                   original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

import numpy as np

def split_array(original_array, axis=0):
    """
    Function to split an array into multiple sub-arrays along a specified axis.
    
    Parameters:
        original_array (numpy.ndarray): Original array to be split.
        axis (int, optional): Axis along which the array will be split. Default is 0.
        
    Returns:
        list: List of sub-arrays.
    """
    sub_arrays = np.split(original_array, indices_or_sections=original_array.shape[axis], axis=axis)
    return sub_arrays

# Given original array
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Call the function and print the list of sub-arrays along axis 0
sub_arrays_axis0 = split_array(original_array, axis=0)
print("List of sub-arrays along axis 0:")
for sub_array in sub_arrays_axis0:
    print(sub_array)

# Call the function and print the list of sub-arrays along axis 1
sub_arrays_axis1 = split_array(original_array, axis=1)
print("\nList of sub-arrays along axis 1:")
for sub_array in sub_arrays_axis1:
    print(sub_array)


List of sub-arrays along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

List of sub-arrays along axis 1:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [2]:
# Write a function that inserts and then deletes elements from a given array at specified indices.
#                        original_array = np.array([1, 2, 3, 4, 5])
#                        indices_to_insert = [2, 4]
#                        values_to_insert = [10, 11]
#                        indices_to_delete = [1, 3]

import numpy as np

def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    """
    Function to insert and delete elements from a given array at specified indices.
    
    Parameters:
        original_array (numpy.ndarray): Original array.
        indices_to_insert (list): List of indices where elements will be inserted.
        values_to_insert (list): List of values to insert at the specified indices.
        indices_to_delete (list): List of indices of elements to delete.
        
    Returns:
        numpy.ndarray: Modified array after insertion and deletion.
    """
    # Insert elements at specified indices
    for idx, val in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, idx, val)
    
    # Delete elements at specified indices
    original_array = np.delete(original_array, indices_to_delete)
    
    return original_array

# Given arrays and indices
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

# Call the function and print the modified array
modified_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Modified array:")
print(modified_array)


Modified array:
[ 1 10 11  4  5]


In [8]:
#  Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
#  Perform element-wise addition between `arr1` and `arr2`.

import numpy as np

# Create array arr1 with random integers
arr1 = np.random.randint(1, 100, size=(5, 5))  # Example: 5x5 array of random integers between 1 and 100

# Create array arr2 with integers from 1 to 10
arr2 = np.random.randint(1, 11, size=(5,5))

# Perform element-wise addition between arr1 and arr2
result_array = (arr1 + arr2)

# Print the result
print("Result of element-wise addition:")
print(result_array)


Result of element-wise addition:
[[27 38 18 21 96]
 [23 60 22 61  9]
 [39 95 92 97 79]
 [23 14 82 47 42]
 [71 45  5 74 84]]


In [9]:
# Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
# from 1 to 10. Subtract `arr2` from `arr1` element-wise.

import numpy as np

# Generate array arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Generate array arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Subtract arr2 from arr1 element-wise
result = arr1 - arr2

# Print the result
print("Result of subtracting arr2 from arr1 element-wise:")
print(result)


Result of subtracting arr2 from arr1 element-wise:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [12]:
#  Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
# Perform element-wise multiplication between `arr1` and `arr2`.

import numpy as np

# Create array arr1 with random integers
arr1 = np.random.randint(1, 100, size=(3, 3))  # Example: 3x3 array of random integers between 1 and 100

# Create array arr2 with integers from 1 to 5
arr2 = np.random.randint(1, 6, size=(3 ,3))

# Perform element-wise multiplication between arr1 and arr2
result_array = arr1 * arr2

# Print the result
print("Result of element-wise multiplication:")
print(result_array)


Result of element-wise multiplication:
[[ 55 132  40]
 [216  38 450]
 [ 78 244 158]]


In [13]:
# Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
# to 5. Perform element-wise division of `arr1` by `arr2`.

import numpy as np

# Generate array arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)

# Create array arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise division between arr1 and arr2
result_array = arr1 / arr2

# Print the result
print("Result of element-wise division:")
print(result_array)


Result of element-wise division:
[2. 2. 2. 2. 2.]


In [15]:
# Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
# reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

import numpy as np

# Create array arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)

# Create array arr2 with the same numbers reversed
arr2 = arr1[::-1]

# Calculate the exponentiation of arr1 raised to the power of arr2 element-wise
result_array = np.power(arr1, arr2)

# Print the result
print("Result of exponentiation of arr1 raised to the power of arr2 element-wise:")
print(result_array)


Result of exponentiation of arr1 raised to the power of arr2 element-wise:
[ 1 16 27 16  5]


In [16]:
#  Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
#                 arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

import numpy as np

def count_substring_occurrences(arr, substring):
    """
    Count the occurrences of a specific substring within a NumPy array of strings.

    Parameters:
        arr (numpy.ndarray): NumPy array of strings.
        substring (str): Substring to count occurrences of.

    Returns:
        int: Number of occurrences of the substring.
    """
    # Count occurrences of the substring in each string
    occurrences = np.char.count(arr, substring).sum()

    return occurrences

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
print("Occurrences of '{}' in the array: {}".format(substring, count_substring_occurrences(arr, substring)))


Occurrences of 'hello' in the array: 3


In [17]:
# Write a function that extracts uppercase characters from a NumPy array of strings.
#               arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

import numpy as np

def extract_uppercase_chars(arr):
    """
    Extract uppercase characters from a NumPy array of strings.

    Parameters:
        arr (numpy.ndarray): NumPy array of strings.

    Returns:
        str: Concatenated uppercase characters extracted from the array.
    """
    # Concatenate all strings in the array
    all_strings = ''.join(arr)

    # Extract uppercase characters
    uppercase_chars = ''.join(char for char in all_strings if char.isupper())

    return uppercase_chars

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
print("Uppercase characters in the array:", extract_uppercase_chars(arr))


Uppercase characters in the array: HWOAIGPT


In [18]:
#  Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
#                     arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

import numpy as np

def replace_substring(arr, old_substring, new_substring):
    """
    Replace occurrences of a substring in a NumPy array of strings with a new string.

    Parameters:
        arr (numpy.ndarray): NumPy array of strings.
        old_substring (str): Substring to be replaced.
        new_substring (str): New substring to replace the old substring.

    Returns:
        numpy.ndarray: NumPy array with replaced substrings.
    """
    # Use np.char.replace() to replace occurrences of old_substring with new_substring
    replaced_array = np.char.replace(arr, old_substring, new_substring)

    return replaced_array

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'
print("Original array:", arr)
print("Array with replaced substring:", replace_substring(arr, old_substring, new_substring))


Original array: ['apple' 'banana' 'grape' 'pineapple']
Array with replaced substring: ['orange' 'banana' 'grape' 'pineorange']


In [19]:
# Write a function that concatenates strings in a NumPy array element-wise.
#                          arr1 = np.array(['Hello', 'World'])
#                          arr2 = np.array(['Open', 'AI'])

import numpy as np

def concatenate_strings(arr1, arr2):
    """
    Concatenate strings in two NumPy arrays element-wise.

    Parameters:
        arr1 (numpy.ndarray): First NumPy array of strings.
        arr2 (numpy.ndarray): Second NumPy array of strings.

    Returns:
        numpy.ndarray: NumPy array with concatenated strings.
    """
    # Use np.char.add() to concatenate strings element-wise
    concatenated_array = np.char.add(arr1, arr2)

    return concatenated_array

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
print("Concatenated array:", concatenate_strings(arr1, arr2))


Concatenated array: ['HelloOpen' 'WorldAI']


In [20]:
# Write a function that finds the length of the longest string in a NumPy array.
#               arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

import numpy as np

def longest_string_length(arr):
    """
    Find the length of the longest string in a NumPy array.

    Parameters:
        arr (numpy.ndarray): NumPy array of strings.

    Returns:
        int: Length of the longest string.
    """
    # Use np.char.str_len() to find the lengths of all strings in the array
    string_lengths = np.char.str_len(arr)

    # Find the maximum length among the strings
    max_length = np.max(string_lengths)

    return max_length

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print("Length of the longest string:", longest_string_length(arr))


Length of the longest string: 9
