In [1]:
#  Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
# with a given step size.

import numpy as np

def create_integer_array(start, stop, step):
    """
    Creates a NumPy array of integers within a specified range (inclusive) with a given step size.
    
    Parameters:
        start (int): Starting value of the range.
        stop (int): Ending value of the range (inclusive).
        step (int): Step size between each value in the range.
    
    Returns:
        numpy.ndarray: NumPy array containing the integers within the specified range.
    """
    return np.arange(start, stop+1, step, dtype=int)

start = 1
stop = 10
step = 2
integer_array = create_integer_array(start, stop, step)
print("NumPy array of integers within the range", start, "to", stop, "with step size", step, ":\n", integer_array)


NumPy array of integers within the range 1 to 10 with step size 2 :
 [1 3 5 7 9]


In [2]:
#  Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

import numpy as np

def generate_equally_spaced_values():
    """
    Generates a NumPy array of 10 equally spaced values between 0 and 1 (inclusive).
    
    Returns:
        numpy.ndarray: NumPy array containing the equally spaced values.
    """
    return np.linspace(0, 1, num=10)

equally_spaced_array = generate_equally_spaced_values()
print("NumPy array of 10 equally spaced values between 0 and 1 (inclusive):\n", equally_spaced_array)


NumPy array of 10 equally spaced values between 0 and 1 (inclusive):
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [5]:
# Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

import numpy as np

def generate_logarithmically_spaced_values():
    """
    Generates a NumPy array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
    
    Returns:
        numpy.ndarray: NumPy array containing the logarithmically spaced values.
    """
    return np.logspace(0, 3, num=5)

logarithmically_spaced_array = generate_logarithmically_spaced_values()
print("NumPy array of 5 logarithmically spaced values between 1 and 1000 (inclusive):\n", logarithmically_spaced_array)


NumPy array of 5 logarithmically spaced values between 1 and 1000 (inclusive):
 [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [7]:
#  Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
# are random integers between 1 and 100.

import numpy as np
import pandas as pd

# Generate a NumPy array of random integers between 1 and 100
data = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame using the NumPy array
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])

# Print the DataFrame
print("Pandas DataFrame:")
print(df)


Pandas DataFrame:
   Column1  Column2  Column3
0       66       40       88
1       47       89       82
2       38       26       78
3       73       10       21
4       81       70       80


In [8]:
#  Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use
# NumPy operations within the Pandas DataFrame.

import pandas as pd
import numpy as np

def replace_negative_with_zeros(df, column_name):
    """
    Replaces all negative values in a specific column of a Pandas DataFrame with zeros.
    
    Parameters:
        df (pandas.DataFrame): The Pandas DataFrame.
        column_name (str): The name of the column containing the values to be replaced.
    
    Returns:
        pandas.DataFrame: The modified Pandas DataFrame with negative values replaced by zeros.
    """
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

data = {'A': [-1, 2, -3, 4, 5],
        'B': [6, -7, 8, -9, 10]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df_modified = replace_negative_with_zeros(df, 'A')

print("\nDataFrame after replacing negative values in column 'A' with zeros:")
print(df_modified)


Original DataFrame:
   A   B
0 -1   6
1  2  -7
2 -3   8
3  4  -9
4  5  10

DataFrame after replacing negative values in column 'A' with zeros:
   A   B
0  0   6
1  2  -7
2  0   8
3  4  -9
4  5  10


In [10]:
# Access the 3rd element from the given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])

import numpy as np

arr = np.array([10, 20, 30, 40, 50])
Third_element = arr[2]

print("Third element of the array:" ,Third_element)

Third element of the array: 30


In [11]:
# Retrieve the element at index (1, 2) from the 2D NumPy array.
#   arr_2d = np.array([[1, 2, 3],
#                    [4, 5, 6],
#                    [7, 8, 9]])

import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element_at_index_1_2 = arr_2d[1, 2]

print("Element at index (1, 2) from the array:", element_at_index_1_2)


Element at index (1, 2) from the array: 6


In [12]:
#  Using boolean indexing, extract elements greater than 5 from the given NumPy array.
#          arr = np.array([3, 8, 2, 10, 5, 7])

import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])

# Create a boolean mask for elements greater than 5
mask = arr > 5

# Use the mask to extract elements greater than 5
elements_greater_than_5 = arr[mask]

print("Elements greater than 5 from the array:", elements_greater_than_5)


Elements greater than 5 from the array: [ 8 10  7]


In [13]:
# Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
#           arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Perform basic slicing to extract elements from index 2 to 5 (inclusive)
sliced_array = arr[2:6]

print("Sliced array from index 2 to 5 (inclusive):", sliced_array)


Sliced array from index 2 to 5 (inclusive): [3 4 5 6]


In [14]:
# Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
#          arr_2d = np.array([[1, 2, 3],
#                            [4, 5, 6],
#                           [7, 8, 9]])

import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]

print("Sub-array [[2, 3], [5, 6]]:")
print(sub_array)


Sub-array [[2, 3], [5, 6]]:
[[2 3]
 [5 6]]


In [19]:
# Write a NumPy function to extract elements in specific order from a given 2D array based on indices 
# provided in another array.

import numpy as np

def extract_elements_in_specific_order(arr_2d, indices):
    """
    Extracts elements from a given 2D array based on indices provided in another array.
    
    Parameters:
        arr_2d (numpy.ndarray): The 2D array from which elements are to be extracted.
        indices (numpy.ndarray): Array containing indices specifying the order of extraction.
    
    Returns:
        numpy.ndarray: Array containing elements extracted from arr_2d in the specified order.
    """
    return arr_2d[np.arange(len(indices)), indices]

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([1, 2, 2])  # Indices specifying the order of extraction

extracted_elements = extract_elements_in_specific_order(arr_2d, indices)

print("Extracted elements in specific order:", extracted_elements)


Extracted elements in specific order: [2 6 9]


In [20]:
#  Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

import numpy as np

def filter_elements_greater_than_threshold(arr, threshold):
   
    return arr[arr > threshold]

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
threshold = 5

filtered_elements = filter_elements_greater_than_threshold(arr, threshold)

print("Filtered elements greater than", threshold, ":", filtered_elements)


Filtered elements greater than 5 : [6 7 8 9]


In [1]:
#  Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
#  separate arrays for each dimension.

import numpy as np

def extract_elements_3d_array(arr_3d, indices_dim1, indices_dim2, indices_dim3):
    """
    Extracts specific elements from a given 3D array using indices provided in three separate arrays
    for each dimension.
    
    Parameters:
        arr_3d (numpy.ndarray): The 3D array from which elements are to be extracted.
        indices_dim1 (numpy.ndarray): Array containing indices for the first dimension.
        indices_dim2 (numpy.ndarray): Array containing indices for the second dimension.
        indices_dim3 (numpy.ndarray): Array containing indices for the third dimension.
    
    Returns:
        numpy.ndarray: Array containing elements extracted from arr_3d using the provided indices.
    """
    return arr_3d[indices_dim1, indices_dim2, indices_dim3]

arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   
                   [[7, 8, 9],
                    [10, 11, 12]]])

indices_dim1 = np.array([0, 1])
indices_dim2 = np.array([0, 1])
indices_dim3 = np.array([1, 2])

extracted_elements = extract_elements_3d_array(arr_3d, indices_dim1, indices_dim2, indices_dim3)

print("Extracted elements from the 3D array:")
print(extracted_elements)




Extracted elements from the 3D array:
[ 2 12]


In [1]:
#  Write a NumPy function that returns elements from an array where both two conditions are satisfied
# using boolean indexing.

import numpy as np

def elements_satisfying_conditions(arr, condition1, condition2):
    """
    Returns elements from an array where both two conditions are satisfied using boolean indexing.
    
    Parameters:
        arr (numpy.ndarray): The input array.
        condition1 (numpy.ndarray): Boolean array specifying the first condition.
        condition2 (numpy.ndarray): Boolean array specifying the second condition.
    
    Returns:
        numpy.ndarray: Array containing elements from arr where both conditions are satisfied.
    """
    return arr[np.logical_and(condition1, condition2)]

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
condition1 = arr > 3  # Elements greater than 3
condition2 = arr % 2 == 0  # Even elements

satisfied_elements = elements_satisfying_conditions(arr, condition1, condition2)

print("Elements from the array where both conditions are satisfied:", satisfied_elements)


Elements from the array where both conditions are satisfied: [4 6 8]


In [2]:
# Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

import numpy as np

def extract_elements_2d_array(arr_2d, row_indices, col_indices):
    """
    Extracts elements from a 2D array using row and column indices provided in separate arrays.
    
    Parameters:
        arr_2d (numpy.ndarray): The 2D array from which elements are to be extracted.
        row_indices (numpy.ndarray): Array containing row indices.
        col_indices (numpy.ndarray): Array containing column indices.
    
    Returns:
        numpy.ndarray: Array containing elements extracted from arr_2d using the provided row and column indices.
    """
    return arr_2d[row_indices, col_indices]

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_indices = np.array([0, 1, 2])  # Row indices
col_indices = np.array([0, 2, 1])  # Column indices

extracted_elements = extract_elements_2d_array(arr_2d, row_indices, col_indices)

print("Extracted elements from the 2D array:")
print(extracted_elements)


Extracted elements from the 2D array:
[1 6 8]


In [3]:
# Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

import numpy as np

# Given array arr of shape (3, 3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add a scalar value of 5 to each element using broadcasting
result = arr + 5

print("Original array:")
print(arr)

print("\nArray after adding a scalar value of 5 to each element:")
print(result)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after adding a scalar value of 5 to each element:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [6]:
# Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
# corresponding element in arr1 using NumPy broadcasting.

import numpy as np

# Given arrays
arr1 = np.array([[2, 3, 4]])  # Shape: (1, 3)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  # Shape: (3, 4)

# Reshape arr1 to (3, 1) to match the shape of arr2 for broadcasting
arr1_reshaped = arr1.reshape(3, 1)

# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = arr2 * arr1_reshaped

print("Result after multiplying each row of arr2 by the corresponding element in arr1:")
print(result)


Result after multiplying each row of arr2 by the corresponding element in arr1:
[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [7]:
#  Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
# NumPy broadcasting.

import numpy as np

# Given arrays
arr1 = np.array([[1, 2, 3, 4]])  # Shape: (1, 4)
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])  # Shape: (4, 3)

# Reshape arr1 to (4, 1) to match the shape of arr2 for broadcasting
arr1_reshaped = arr1.reshape(4, 1)

# Add arr1 to each row of arr2 using broadcasting
result = arr2 + arr1_reshaped

print("Result after adding arr1 to each row of arr2:")
print(result)


Result after adding arr1 to each row of arr2:
[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [8]:
#  Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

import numpy as np

# Given arrays
arr1 = np.array([[1],
                  [2],
                  [3]])  # Shape: (3, 1)
arr2 = np.array([[4, 5, 6]])  # Shape: (1, 3)

# Add arr1 and arr2 using broadcasting
result = arr1 + arr2

print("Result after adding arr1 and arr2 using broadcasting:")
print(result)


Result after adding arr1 and arr2 using broadcasting:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [13]:
#  Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting.
# Handle the shape incompatibility.

import numpy as np

# Given arrays
arr1 = np.array([[1, 2, 3],
                  [4, 5, 6]])  # Shape: (2, 3)
arr2 = np.array([[7, 8],
                  [9, 10]])  # Shape: (2, 2)

# Add a new axis to arr2 to make its shape compatible with arr1 for broadcasting
arr2_newaxis = arr2[:, :, np.newaxis]  # Adding a new axis along the third dimension

# Perform multiplication using broadcasting
result = arr1 * arr2_newaxis

print("Result after multiplication using NumPy broadcasting with added axis:")
print(result)


Result after multiplication using NumPy broadcasting with added axis:
[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]
